### ISSUE TITLE
Accept some pull requests on this repo automatically

### ISSUE THREAD

**Issue by paf31** [purescript/package-sets#3]
Maybe later?

**Comment by f-f** [comment]
This is quite related to https://github.com/spacchetti/spago/issues/72

Basically the plan there is to have spago spit out a URL to the user so that they can open it in the browser and they will end up opening an issue on this repo following some predefined template. Now since this template is not free-form, there could be some bot (e.g. our dear @spacchettibotti) watch for incoming issues, run some checks, open PRs, merge them once the CI passes, etc.

This issue would build on the one linked above, so I'll leave this open as a reminder to implement this kind of automation
