### ISSUE TITLE
Rename quickcheck

### ISSUE THREAD

**Issue by paf31** [purescript/package-sets#30]
I think it would be good to rename the library to avoid confusion with the Haskell library (also I think the name might be trademarked?)

This was previously tricky since we'd have to rename it in GitHub and Bower, but it's simpler now that we own the "registry" 😄 

So, what should we rename it to?

**Comment by garyb** [comment]
I dunno, there are quite a lot of implementations in other languages that stick to the QuickCheck name. If we had to, "PureCheck" or some slight mutation like that perhaps?

**Comment by paf31** [comment]
I wasn't aware of any other using the exact name, possibly for this reason. Did you find one?

**Comment by Pauan** [comment]
I'm in favor of `purescript-fuzz-test`, since it's a name which is already used for similar concepts in other languages: https://en.wikipedia.org/wiki/Fuzz_testing

Alternatively, `purescript-random-test` is good too.

**Comment by paf31** [comment]
Hmm, some of the names here do contain the word QuickCheck in full, so maybe this isn't worth worrying about?

https://en.wikipedia.org/wiki/QuickCheck

**Comment by garyb** [comment]
A few from wikipedia:
http://software.legiasoft.com/quickcheck/ https://bitbucket.org/blob79/quickcheck https://github.com/pholser/junit-quickcheck/ https://github.com/camlunity/ocaml-quickcheck http://www.swi-prolog.org/pack/list?p=quickcheck https://github.com/RevolutionAnalytics/quickcheck https://github.com/steos/php-quickcheck https://docs.racket-lang.org/quickcheck/index.html

**Comment by garyb** [comment]
Ah, I was too slow :wink:

@Pauan I'd fuzz testing is a bit different, as the idea is to throw random unexpected data at a program in an attempt to crash it, QC is for checking that a property of a function holds no matter what input is given, but the inputs have to be the right type, and also possibly within a particular range to check the property holds for some subset of possible inputs.

Anyway, it's academic now :smile:

**Comment by Pauan** [comment]
@garyb Yes, but ultimately the techniques used are exactly the same: generate random data, then test that it works. The only real difference is that PureScript only needs to generate data of a particular type, because of its strong static typing.

**Note:** fuzz testing isn't only about detecting crashes, it is also used with assertions as well, making it extremely close to QuickCheck.

I'm also in favor of the name `purescript-random-test`, which is even more descriptive than `purescript-fuzz-test`, since it describes exactly what it does: it generates random tests.

If you aren't already familiar with QuickCheck, and you see a package called `purescript-quickcheck`, you have *no idea at all* what it does. But if you see a package called `purescript-random-test`, you have a pretty good idea that it involves unit testing, and that randomness is probably involved in some way.
