### ISSUE TITLE
Include checksums for each package

### ISSUE THREAD

**Issue by Pauan** [purescript/package-sets#32]
This is super-low priority, but I think it would be nice to eventually have checksum information embedded into the `packages.json`

Why? Imagine that the repository `https://github.com/foo/foo.git` is added to the package set with the tag `v1.0.0`

At first, everything is fine. But then later the repository `https://github.com/foo/foo.git` adds in some malicious code and overwrites the `v1.0.0` tag to point to the malicious code. Now everybody who uses that package will end up downloading the malicious code.

But if the checksum for the repository was added to the package set, then `psc-package` could check the checksum after downloading the package `foo`, which would prevent that attack.

Obviously this relies upon `foo` not including any malicious code in the first place, but at least that can be solved by code audits. After a package has been code audited, and the checksum is in place, it is essentially impossible for a malicious change to occur.

(As a side bonus, this also catches any weird network or file system errors that might corrupt the package during download/installation)

On the other hand, if code audits rarely occur, then a checksum could give a false sense of security.

**Comment by paf31** [comment]
👍 Sounds like a good idea.

**Comment by Pauan** [comment]
Also, for the *even more* paranoid, you could create a checksum for the package set itself (including the `packages.json`). This checksum would be placed into the `psc-package.json` file as a new `checksum` field (similar to `set` and `source`)

That means that even if somebody malicious gained access to the package set repo (e.g. `purescript/package-sets`), they *still* wouldn't be able to distribute malicious code, because the package set itself would be checksummed.

Of course `psc-package init` would automatically add in the appropriate `checksum` field, so this would be transparent for users, with no loss of convenience.

Now the entire system (both package set and individual packages) is protected from malicious attacks, so the only parts that need to be trusted are `psc`, `psc-bundle`, and `psc-package` (which can be locally verified, if somebody wished to do so).

I don't think that maliciousness would be a problem for `purescript/package-sets`, but it may be more important if there are alternate package sets created by third parties. I can imagine a third-party package set with a very strict code audit process, which would advertise itself as a "safe alternative to `purescript/package-sets` for enterprises that require maximum safety". Kind of like the OpenBSD of PureScript.

In any case, checksums do not guarantee security, because security *always* requires code audits. And I'm *not* suggesting that `purescript/package-sets` should have strict code audits. Instead, it is more about *enabling* strict code audits, if a third party package set wished to do so.

Also this entire idea is very low priority, as I already mentioned.

**Comment by sudhirvkumar** [comment]
@Pauan 

What if the malicious code is part of v1.0.1? Is there any link where I can learn more about your code audits idea? Because I am paranoid too. We use packages and trust that all the packages will be malicious code free... which is not guaranteed. Our judgement has consequences for our clients. We would like to be extremely careful.

**Comment by Pauan** [comment]
@sudhirvkumar If the library author releases a new version 1.0.1, nobody will be affected by it, because the package set is still using the old 1.0.0 version.

Therefore, they must [send a pull request to the package set, requesting to bump the version](https://github.com/purescript/package-sets/pull/53/files).

At that point, the package set maintainers can look at the new version, make sure it's okay, then accept the pull request.

So the only way for malicious code to get into a package set is if the package set maintainers are malicious, or if the package set maintainers aren't diligent in their audits.

**Comment by sudhirvkumar** [comment]
@Pauan 
this particular PR is understandable, as 0.1.0 & 0.2.0 are breaking changes

But, 1.0.0 & 1.0.1 are not breaking changes but patches and we should be using the latest version 1.0.1 instead of 1.0.0...  I am really not sure.. but my guess is... using ^1.0.0 in the version for the package will use the latest version within the major version...

I have seen instances where I had specified ^2.0.0 and 2.5.0 was installed... need to dig deeper regarding the ^2.0.0 and how psc-package handles it...

**Comment by Pauan** [comment]
No, package sets don't work like that. They don't use semver. *Every* change requires a pull request, even patch changes.

This guarantees that package sets are always consistent, correct, and don't have breaking changes.

**Comment by sudhirvkumar** [comment]
@Pauan good to know... thanks for clearing it up for me! :+1:

**Comment by Pauan** [comment]
@sudhirvkumar [Here's an example of a pull request that bumps patch versions](https://github.com/purescript/package-sets/pull/22/files)

**Comment by Pauan** [comment]
Also, if package sets used semver, when the library author releases a new version, the checksum would be different, so it would cause an error.

So the checksum forces package sets to *not* use semver.

**Comment by sudhirvkumar** [comment]
@Pauan Only thing I am worried about is... if the package authors / somebody else don't open a PR... then we will be using broken / buggy packages which are already solved in the patch versions... I guess there can be some way (Automated) to manage the updates to packages in the package-sets in a timely manner.

**Comment by Pauan** [comment]
Yes, but that's a separate issue. Specifically, https://github.com/purescript/package-sets/issues/3 and https://github.com/purescript/package-sets/issues/6. If a package set cared about security, it could limit automatic pull requests to trusted members.

**Comment by reactormonk** [comment]
Since spago now supports pointing to commit hashes https://github.com/spacchetti/spago/issues/200, should the package set now use these instead of tags?

**Comment by justinwoo** [comment]
i still use psc-package, and i personally think there's value in having actual version numbers and tags over random commits, which can't be efficiently fetched (see details on git fetch and git server implementations not allowing fetching "arbitrary" commit SHA)

**Comment by jmackie** [comment]
I'm keen to make this happen, so here's my proposal:

First we extend the package "type" to include `rev` and `sha256` (see #426 but it's WIP). Tools should then prefer to clone by `rev`, but we leave `version` for humans. Ultimately tools should probably ignore `version` altogether.

In order to actually verify the `sha256` we need `psc-package` and friends to be able to actually compute a checksum on a cloned directory. The first issue then is that there's not really a standard way of hashing a directory. But the closest we have - I'd say - is the way Nix does it. But then we don't want to force the Nix toolchain on everyone/everything, so...

I implemented the `nix-hash` CLI tool (used by `nix-prefetch-git` and friends) in Haskell, which is here https://github.com/jmackie/kesha. If I throw that up on hackage then it would be relatively painless for `psc-package` and `spago` to start performing the checks. And anyone looking to add something to that package-set can `stack install kesha` rather than pulling all the Nix stuff.

So there'd bit a bit of work to do across the repos, and a period of time(?) when we support these checks optionally, but I think generally it should be straightforward. 

Thoughts?

**Comment by f-f** [comment]
Closing, see https://github.com/purescript/package-sets/issues/1042#issuecomment-979936204
