### ISSUE TITLE
ACME-build all packages together to ensure unique module names

### ISSUE THREAD

**Issue by f-f** [purescript/package-sets#490]
We should build all packages together in CI, for several reasons:
- users may face unwanted surprises because of conflicting transitive dependencies
- we can build docs for the whole package set

**Comment by Dretch** [comment]
I could help with this, I think.

It looks like this could be done by changing the behaviour of `psc-package verify` so it compiles everything together (in addition to its current behaviour of compiling each package independently). I think it would make sense to also change `spago verify-set` so it behaves the same way.

However, since `psc-package` is being deprecated, then maybe the change should only be done to Spago? This would also require changing the package-sets CI to use Spago - which would need something to make a spago config with all the packages (like for building all the docs - https://github.com/spacchetti/starsuit/blob/master/index.js).

**Comment by f-f** [comment]
@Dretch yeah I think we should switch the CI to Spago since `psc-package` is being deprecated (cc @justinwoo)

**Comment by f-f** [comment]
This was just fixed in #566, since we started using `spago verify-set` in CI, that does an ACME build since https://github.com/purescript/spago/pull/438
