### ISSUE TITLE
proposal: Few Curation, Automatic PR, Global CI

### ISSUE THREAD

**Issue by rvion** [purescript/package-sets#6]
@paf31 Let's imagine that
-  pursuit db is used as the the list of packages database (no specific curation for now, global db)
- purescript-package-db basically do:
  
  ```
  foreach topologically sorted puresuit packages
     pull latest package version 
     bower update all dependencies to latest version
     try to build
     if not successfull -> open a github issue(s) with build failure detail
     if successfull but declared constraint not uptodate -> open PR with constraint update
     if clever suggestion found -> open an issue or PR
  ```
  
  (bower has commands to update all deps to latests versions, or check if a package has out of date deps)
- `purescript-package-db` can tracks package quality: it checks the package `level of documentation`, `number of warnings`, etc. It could invite people to better document things, remove warning, etc in automatics PR
- `purescript-package-db` could produce **a bower constraint file** for all packages working well together (named like latest-2016-08-05). (same as stackage)
- on pursuit, we could show if
  - deps are out of date ( orange if it builds fine with dependencies version bump,  red it it doesn't compile with after version bump)
  - number of warning
  - various quality stats
- IMO automatic PR automatically are much more useful than curation for now. `purescript-package-db` could invite package author to help fixing dependant packages breaking after an update, etc. Stackage is a good inspiration, but since purescript ecosystem is not so mature yet, this kind of global CI would help the package ecosystem to mature faster.
- without curation, no need for things like https://github.com/paf31/purescript-package-db/issues/3 right now
- purescript-package-db could prioritize open source effort based on download count, reverse dependencies, etc, and suggest volunteers specific packages to work on

**Comment by rvion** [comment]
all of that could then be integrated on the official website.
 - news.purescript.org for news
 - libraries.purescript.org (to replace pursuit, `libraries` is more wide-spread than `package` amongst programmers) this page would also display metrics from `purescript-package-db`
 - ci.purescript.org would show purescript-package-db specific thins (ci output, etc.)

etc.

and the top level menu could also display libraries, news, etc. alongside home, download

![image](https://cloud.githubusercontent.com/assets/2150990/18814118/d1bb6fe6-8310-11e6-844d-3ad99e63c6da.png)

**Comment by paf31** [comment]
Thanks for writing this up. There are a lot of good ideas here which can probably become their own issues.

> pursuit db is used as the the list of packages database

Eventually, I can see these two tools getting unified, but I'd prefer to keep them separate for now.

> purescript-package-db can tracks package quality

Ideally, I think we'd enforce a minimum level of documentation, no warnings etc. when a package is added to the set.

> purescript-package-db could produce a bower constraint file for all packages working well together

Sounds sensible, and I think this is a great way to continue to use Bower in the short term.

> IMO automatic PR automatically are much more useful than curation for now.

I would like to automatically accept single package additions and package updates if they pass CI.

**Comment by rvion** [comment]
thanks 

small typo and lack of clarity here: 

> IMO automatic PR automatically are much more useful than curation for now. 

I was speaking about the possibility for purescript-package-db to open automatically PR and issues on github repos for {packages in the set / all packages known} so author have less manual work to do. 

purescript-package-db could 

open PR for
  - dependency version bump in case of out of date dependencies
  - adding a travis.yaml file along mini tuto explanation
  - specific refactoring provided by some future special auto-upgrade file
  - etc. (insert many ideas here, like specific refactoring provided by some future special auto-upgrade file,..)


and open issues for 
 - build error
 - too many warnings
 - lack of documentation
 - etc.

purescript-package-db would just host 
  - code quality infos, warnings, doc quality
  - build infos
  - documentation
  - ...and later, manual "curated by admin" flags

The idea here is not to build a curation tool, but rather a helping semi-automatic bot that check purescript packages infos, update a user-visible database, and automatically open PR, 

@paf31  My point is that __all__ packages could benefit this kind of feedback and automatic issues and PR. I think the whole ecosystem would move faster without an extra step of curation in the middle.

**Comment by paf31** [comment]
I don't think many of those PRs are necessary though. We just shouldn't allow packages into the set if they don't meet the criteria, and if they meet the criteria today, they should always do so, by virtue of the set only growing monotonically in terms of packages and their versions.

For example, version information won't become out of date because we always use the version in the JSON file. If we're using semver properly, then it should be safe to make a minor version bump for any package. Major bumps will necessitate an entirely new package set (actually I should create an issue to support multiple sets).

**Comment by rvion** [comment]
@paf31 

> I don't think many of those PRs are necessary though. 

they could be opt-in by packages author via the purescript-package-db web interface.  

> We just shouldn't allow packages into the set if they don't meet the criteria

I understand well how stackage works, but I was suggesting not to do exactly like stackage for now.

if purescript-package-db have information about packages quality, via 
  1. automatically computed package quality
  2. manually checked-in packages by admins

then it can: 
  - for a given set of packages, find a working set of packages working well together including wanted packages
  - build a stackage-like set of largest subset of packages working together, including one-by-one most used packages from the manually checked-in package list, following import order, and most used order when several possibilities, and then adding all non checked-in remaining packages from the set.


In the end, it's better than stackage (IMO), yet simpler

**Comment by hdgarrood** [comment]
I think we need to clarify this and split it up into individual issues, since the landscape has changed significantly since it was first opened. I think there are a few different issues here:

* Put together a global CI for purescript packages which tries to build downstream packages when upstream packages change, and can notify package authors when their dependencies are updated
  * This could be a good thing; as I understand it, packages are only updated in the package set when someone manually updates them right now. Personally, I'd prefer to have this CI tool only try to build packages which are in the current version of the package set here, rather than trying to build everything on Pursuit. My reason for this is twofold: firstly, we already have the information needed for this task (i.e. what depends on what) in the data inside this repo, and secondly, I don't think we should assume authors are interested in these PRs by default, but if they have submitted their packages to package-sets, then it's more likely that they will want to hear about upstream updates so that they can keep their packages up to date.
* Produce a bower constraint file so that people can make use of package sets together with bower.
  * This is something which might be useful, but probably only in rare cases these days: if you want to use package sets, the natural way of doing that is via Spago.
* Invite people to better document things, remove warnings, etc in automatic PRs
  * I'm very much not in favour of this. We shouldn't have bots badgering people to improve their package documentation because that's poor OSS etiquette. It's especially poor etiquette if it's being done by a bot, since bots can't distinguish good documentation from bad documentation which was only put there to shut them up. I'm _extremely_ not keen on calculating quality stats and displaying them on Pursuit, mainly because these are realistically just going to be easily-gamed metrics which have little to do with actual quality, but also because it will contribute to maintainer pressure and guilt.
* Write a tool to allow packages to be upgraded in an automatic manner; perhaps provide a way for package authors to indicate how downstream packages need to be updated after an update in a machine-readable way.
  * This would be really cool if someone managed to pull it off, but in any case it should be tracked outside this repository.

**Comment by f-f** [comment]
The [alpha for the new Registry](https://discourse.purescript.org/t/registry-alpha-launched/3146) has now launched, and this entails the automation of this repository - packages in the set will be managed through [the new API](https://github.com/purescript/registry#modify-the-package-set), and a new release will be cut once a day if there are any new updates.

I believe we got as close as possible to what's described here (since we try to add every new package to the latest package set) and any improvement over this should be suggested [in the Registry repo.](https://github.com/purescript/registry)
