### ISSUE TITLE
move all paf31 deprecated packages to purescript-contrib OR create a new organization

### ISSUE THREAD

**Issue by srghma** [purescript/package-sets#856]
packages are here https://github.com/purescript/package-sets/blob/master/src/groups/paf31.dhall

cannot update optparse https://github.com/f-o-a-m/purescript-optparse/pull/23

because https://github.com/paf31/purescript-memoize is deprecated

Q: what is better:
1. move them to https://github.com/purescript-contrib/
2. or create a new org https://github.com/purescript-paf31-packages

P.S. https://github.com/paf31/purescript-event package became https://github.com/purescript-halogen/purescript-halogen-subscriptions/

**Comment by JordanMartinez** [comment]
Per the [`purescript-contrib` library guidelines](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md#expectations-for-libraries), a library will only be accepted if we have a maintainer assigned to it. I don't know if other members of the `purescript-contrib` org want to maintain these libraries. I'm a member, but I do not want to maintain them.

On one hand, making a GH organization called `purescript-paf31-packages` seems a bit weird. I imagine that Phil would be annoyed if someone started pinging him for help because his username is a part of the organization's name.
On another hand, he is the original author and I'm not sure what name should be used for such an organization otherwise.

Another alternative is for various members of the PureScript community to fork the libraries and call them something else (e.g. `event` -> `halogen-subscriptions`), depending on what they need.

**Comment by thomashoneyman** [comment]
Yea, we've opted not to fork and maintain any of these libraries in `contrib`. The `halogen-subscriptions` library is a take on `event` that the Halogen organization is taking over maintenance of.

For any other library the community wants to maintain, individuals should fork and rename the library. For optparse specifically it may be best to try and drop the dependency.

**Comment by srghma** [comment]
> On one hand, making a GH organization called purescript-paf31-packages seems a bit weird. I imagine that Phil would be annoyed if someone started pinging him for help because his username is a part of the organization's name

Probably that's the best alternative
We can write `these are the packages abandoned by Phil. Please don't ping him for help`

> For optparse specifically it may be best to try and drop the dependency.

There are lot of other good abandoned packages, I don't think it's a solution

> I don't know if other members of the purescript-contrib org want to maintain these libraries

With automated prs to package-sets on every new tag it would be easier to maintain them.

> individuals should fork and rename the library

@thomashoneyman then, to make pr to package-sets, should I not only create an org, BUT also rename each package? Even if package is abandoned?

P.S. optparse itself is probably abandoned

**Comment by CarstenKoenig** [comment]
I'm no member of any organizations but I would be willing to maintain one or two packages - I'm sure there are lot's of other possible volunteers ;)

Please feel free to ping me about this or point me to where to "apply" or whatever.

PS: Sorry if this interrupts this discussion or if this is out of scope - let's me know and I'll remove the comment then.

**Comment by f-f** [comment]
@srghma yes, the current recommendation if you want to register a forked package is to rename it.
We are not going to transfer the names from these libraries from the registry, because they are well known packages and the author has explicitly archived them, and we should respect that. Downstream users should make the conscious choice of switching to the new library, as reusing the same name would be misleading.

**Comment by thomashoneyman** [comment]
I think it's reasonable to take this approach, if you do want to continue a library that is now unmaintained:

1. Name the library something new so it can be added to the registry and package sets
2. Acknowledge the original library either by explicitly forking it or, if rewriting, linking somewhere prominently in the README so as to give credit. I'd avoid saying the author 'abandoned' the package or anything like that -- clicking through to see the original package was archived is enough to know that the original is unmaintained.
3. Avoid using the original author's username in the new organization or library names

**Comment by srghma** [comment]
@thomashoneyman @f-f 

how would you suggest to name the organization if not `purescript-paf31-packages` and not `purescript-abandoned` (and write "this organization is for all packages that were archived or abandoned, anyone can become an organization member")?

`purescript-archived-packages`?

**Comment by JordanMartinez** [comment]
@srghma How about `purescript-miscellaneous` as an org name?

**Comment by thomashoneyman** [comment]
@srghma I guess I would suggest waiting a while to see if libraries are forked by folks who intend to maintain them for a while; there are now forks or adaptions of `event` (now `halogen-subscriptions`) and `drawing` (now `painting`) at least. Perhaps more libraries will be forked in the future.

If you need a library only because it's a dependency of a dependency then I would probably focus on removing the dependency by updating the code rather than fork the library, unless you plan to maintain it for the next compiler release or longer.

If you do have interest in forking and maintaining a particular library then you could definitely make an organization like `purescript-miscellaneous` or you could fork them to your personal account and rename them.

In the specific case of `optparse` I might open an issue there saying that `memoize` is archived and seeing if they'd like to drop the dependency in order to update to 0.14. Unfortunately, I haven't seen activity on that repo in some time; I'm not sure how responsive the maintainers will be.

In any case, this is how I would personally approach this and I hope it's helpful, but there isn't a set rule here about what specifically to do.

**Comment by f-f** [comment]
Is there something actionable we can do here in `package-sets` about this or should we close this?

**Comment by srghma** [comment]
In @hdgarrood post https://discourse.purescript.org/t/proposal-on-purescript-package-management/2245/8


There is a link to https://samsieber.tech/posts/2020/09/registry-structure-influence/

> While there are negative aspects of a flat package registry, there are also real benefits. Stability, continuity, and unity (discourages forks and fragmented identity). Proposals that seek to add namespacing without addressing the positive aspects they remove probably won’t be accepted.

______

N.B. for new participants: current state is - https://github.com/f-o-a-m/purescript-optparse is not deprecated, but outdated / broken / commented out 

https://github.com/paf31/purescript-memoize is deprecated

_____

IF namespaces are such a bad thing AND we want unity
THEN 

regarding @f-f comment

> Using something like optparse2 should be fine.

And Thomas comment

> then you could definitely make an organization like purescript-miscellaneous or you could fork them to your personal account and rename them

Re memoize and other deprecated packages, we can:
- fork, rename to memoize2 and ....2 and add them to package-sets - but there is no unification, no discouragement of duplicates
- fork memoize and others, don't rename, just change url in package-sets - I like this, improbable that packages will be UNdeprecated, community will only say "thank you" that they don't need to change anything

Re optparse, we can:
- optparse2 - this is safe
- fork optparse and change url - not safe, but pro-unity

**Comment by srghma** [comment]
@thomashoneyman could you fork https://github.com/paf31/purescript-memoize to https://github.com/purescript-contrib, I'm willing to be a maintainer

this is better than creating new org

I also propose to not change name to `memoize2`, just change url

_____


as of other packages in https://github.com/purescript/package-sets/blob/master/src/groups/paf31.dhall

https://github.com/paf31/purescript-folds
https://github.com/paf31/purescript-behaviors
https://github.com/paf31/purescript-pairing

I dont need them now, maybe someone else in future will take care of them

_____

I have also the question: what are requirements for being a maintainer at purescript-contrib? E.g. is CHANGELOG required?

**Comment by f-f** [comment]
@srghma I don't think "just changing the URL" is acceptable here, unless the original maintainer explicitly approves it.

I am also not sure this is worth forking in contrib - why not just fork the package under your username?

**Comment by thomashoneyman** [comment]
@srghma These are the guidelines for libraries in the `contrib` organization:
https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md

I'm not sure I'd like to maintain `memoize` as part of the `contrib` organization since it's not used by any of the core, contrib, web, or node packages, or our infrastructure, and it's only really being maintained to continue support for `optparse`. With that in mind, perhaps you'd like to fork it to your account as @f-f suggested?

**Comment by srghma** [comment]
> why not just fork the package under your username since you'd be the maintainer anyways

I dont want to be alone

created https://github.com/purescript-open-community/

made a pr https://github.com/purescript/package-sets/pull/921

the idea of this org is to maintain deprecated packages AND everyone are admins in this org

@CarstenKoenig will add you to the organization, since you wanted
