### ISSUE TITLE
Add the supported compiler versions to the package set JSON

### ISSUE THREAD

**Issue by polux** [purescript/package-sets#96]
See https://github.com/purescript/psc-package/issues/47 for context.

**Comment by nwolverson** [comment]
Unless I'm missing something this needs a (breaking) JSON structure change because the packages are listed at top level, i.e. psc-package change?

**Comment by f-f** [comment]
The package-set tags include the compiler version they are compatible with, and that should be enough for tools to apply SemVer.
E.g. if a package-set is compatible with purs `0.12.2`, then your build tool (`pulp` or `spago` at the time of writing) should allow you to run if you have `0.12.3`, but not if you have `0.12.1`, or `0.13.x`.

As @nwolverson mentioned above, including the versions inside the file would be useful (e.g. when you import the package-set file via a hash instead of a tag), but it's probably too breaking at this point.

So I'll close this one for now, but feel free to reopen if I missed something or it turns out we can do this without much breakage

**Comment by f-f** [comment]
I'd like to reopen this issue, because I now think it would be useful and viable to include things like the minumum supported `purs` version inside some data structure in this repo.

This has several advantages:
- allows package managers to check for the minumum version even if the set is not coming from a github tag, but e.g. saved locally
- it can be done in a backwards-compatible manner: I propose we introduce a `packageSet.dhall` that looks something like `{ minPursVersion = "0.12.5", packages = ./packages.dhall }`
- given the above, this gives us a more versatile data structure for eventually adding more metadata to the package set (e.g. things like "module to package" metadata)

**Comment by f-f** [comment]
I just realized we could implement this in a backwards-compatible way: we can add a bogus package with a name that cannot be used by packages (e.g. `__metadata` or something like that) containing metadata about the set, like the minimum compiler version

@justinwoo opinions?

**Comment by justinwoo** [comment]
maybe that's fine. hopefully there isn't a purescript-__metadata published on bower anytime soon

**Comment by f-f** [comment]
Cool. I'll look into characters banned from bower package names, since I suspect Dhall supports a bigger range in record keys

**Comment by justinwoo** [comment]
馬 ~/Code/purescript-__metadata master (1) $ pu version
* Checking your package using purs publish...
There is a problem with your package, which meant that it could not be
published.
Details:
  There was a problem with your package manifest file:
    At the path: ["name"]
    Invalid package name: The following characters are not permitted in package
    names: _ _

  Please ensure that your package manifest file is valid.
* ERROR: Subcommand terminated with exit code 1

**Comment by f-f** [comment]
While implementing this I realized that in order for this to be truly backwards compatible we have to either:
1. use the same schema as other packages for this metadata (i.e. a record with `version`, `dependencies`, etc) - this might work for now, but it's unpractical in the long term
2. or we use the schema we want for the `__metadata` package, but we filter it out when converting to JSON (both here and in `spago psc-package-insdhall`) so that `psc-package` never sees it and it's happy

**Comment by f-f** [comment]
As per @justinwoo suggestion, I'll make a bower package that follows the compiler's versioning, and just add it as a normal package there. This means that if we want more metadata we can always add some files inside the package itself.
